server.port: 8083

# just mentioning it here for later discussion when we visit
# spring cloud config server
#spring.cloud.config.server.url = http://config-server:8888

spring:
  application.name: spring-boot-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

queue:
  name: "ens-queue"

otp:  "otpQueue"

twilio:
  account:
    sid: "${TWILLIO_SID}"
  auth:
    token: "${TWILLIO_TOKEN}"
  phone:
    from: "+1x6475404420"